"""add initiative_bonus to character

Revision ID: 1137750db56e
Revises: a39e10fae720
Create Date: 2026-03-13 18:51:43.985886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1137750db56e'
down_revision = 'a39e10fae720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initiative_bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('initiative_bonus')

    # ### end Alembic commands ###
