"""add weapon_index and magic_bonus to inventory_items

Revision ID: 2b59ddd9c0f4
Revises: 67ce322d4f42
Create Date: 2026-03-13 21:53:54.232458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b59ddd9c0f4'
down_revision = '67ce322d4f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weapon_index', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('magic_bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('magic_bonus')
        batch_op.drop_column('weapon_index')

    # ### end Alembic commands ###
