"""add invite token expiry

Revision ID: 67ce322d4f42
Revises: 85a7fe727228
Create Date: 2026-03-13 19:33:49.458957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ce322d4f42'
down_revision = '85a7fe727228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
