"""add gender, backstory, portrait_url

Revision ID: 85a7fe727228
Revises: 1137750db56e
Create Date: 2026-03-13 19:06:21.456251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a7fe727228'
down_revision = '1137750db56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('backstory', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portrait_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('portrait_url')
        batch_op.drop_column('backstory')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
